#!/bin/bash

run_hook() {
    echo "=== 2 factor ==="
    echo -n "enter passwd: "
    read -rs USER_PASS
    for i in {1..10}; do
        [ -b /dev/sdb1 ] && break
        echo "waiting for disk..."
        sleep 1
    done
    if [ ! -b /dev/sdb1 ]; then
        echo "no /dev/sdb1"
        sleep 15
        exit 1
    fi
    echo "Connecting to network via DHCP..."
    ip link set eth0 up
    if ip addr show dev eth0 | grep -q "inet "; then
        echo "DHCP lease acquired on eth0."
    else
        ip addr add 10.0.2.15/24 dev eth0
        ip route add default via 10.0.2.2 dev eth0
        echo "nameserver 8.8.8.8" > /etc/resolv.conf
    fi

    export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

    echo "=== network check ==="
    if curl https://google.com | grep -iq "<html"; then
        echo "network is working got google html."
    else
        echo "network is not working"
        sleep 20
        exit 1
    fi
    device_id= # getting from installer
    timestamp=$(date +%s)
    message="$timestamp"
    secret_key="$device_id"

    signature=$(echo -n "$message" | openssl dgst -sha256 -hmac "$secret_key" | cut -d " " -f2)
    response=$(curl -s -w "%{http_code}" -o temp_response.txt 10.0.2.2:8000/client/decrypt \
  -H "X-DeviceId: $device_id" \
  -H "X-Timestamp: $timestamp" \
  -H "X-Signature: $signature")

    if [ "$response" -eq 200 ]; then
        token=$(cat temp_response.txt)
    else
        echo "DEVICE IS STOLEN!!!"
        sleep 15
    fi

    rm -f temp_response.txt
    echo "decrypting.."
    modprobe dm-crypt
    echo "${USER_PASS}${token}" | cryptsetup luksOpen /dev/sdb1 cryptroot || {
        echo "can't decrypt"
        sleep 15
        exit 1
    }

}
