#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description="Render /etc/corepost-preboot.conf from a provisioning bundle.")
    parser.add_argument("--bundle-json", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--server-url", required=True)
    parser.add_argument("--luks-device", default="/dev/corepost-preboot-demo-luks")
    parser.add_argument("--luks-name", default="corepost-demo-crypt")
    parser.add_argument("--usb-key-path", default="/dev/disk/by-label/COREPOST_USB")
    parser.add_argument("--network-iface", default="auto")
    parser.add_argument("--network-failure-policy", choices=("deny", "shell"), default="deny")
    parser.add_argument("--request-retries", type=int, default=3)
    parser.add_argument("--request-retry-delay-seconds", type=int, default=2)
    parser.add_argument("--server-connect-timeout-seconds", type=int, default=5)
    parser.add_argument("--server-max-time-seconds", type=int, default=20)
    args = parser.parse_args()

    bundle = json.loads(args.bundle_json.read_text())
    required_keys = ("deviceId", "deviceSecret", "unlockProfile")
    missing = [key for key in required_keys if not bundle.get(key)]
    if missing:
        raise SystemExit(f"bundle is missing required keys: {', '.join(missing)}")

    config = f"""# Generated by scripts/render-config.py
COREPOST_SERVER_URL="{args.server_url}"
COREPOST_DEVICE_ID="{bundle['deviceId']}"
COREPOST_DEVICE_SECRET="{bundle['deviceSecret']}"
COREPOST_UNLOCK_PROFILE="{bundle['unlockProfile']}"
COREPOST_USB_KEY_PATH="{args.usb_key_path}"
COREPOST_NETWORK_IFACE="{args.network_iface}"
COREPOST_NETWORK_TIMEOUT_SECONDS="20"
COREPOST_NETWORK_FAILURE_POLICY="{args.network_failure_policy}"
COREPOST_REQUEST_RETRIES="{args.request_retries}"
COREPOST_REQUEST_RETRY_DELAY_SECONDS="{args.request_retry_delay_seconds}"
COREPOST_SERVER_CONNECT_TIMEOUT_SECONDS="{args.server_connect_timeout_seconds}"
COREPOST_SERVER_MAX_TIME_SECONDS="{args.server_max_time_seconds}"
COREPOST_LUKS_DEVICE="{args.luks_device}"
COREPOST_LUKS_NAME="{args.luks_name}"
"""

    args.output.write_text(config)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
